base:
  project: Deep Learning Brain Tumor

data_source:
  data_src: source_data

load_data:
  num_classes: 4
  raw_data: source_data
  preprocessed_data: data/processed
  full_path: internship/source_data

train_split:
  split_ration: 80

model:
  name: VGG19
  trainable: False
  train_path: data/processed/train
  test_path: data/processed/test
  image_size: [255,255]
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: ['accuracy']
  epochs: 1
  save_dir: models/trained.h5

img_augment:
  rescale: 1./255,
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True
  batch_size: 18
  class_mode: 'categorical'

model_dir: models

mlflow_config_deep:
  artifacts_deep_dir: artifacts
  experiment_name: Deep_Learning_VGG19
  run_name: deep_mlops
  registered_deep_model_name: Deep_Learning
  remote_server_uri: http://127.0.0.1:5000
