version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser &&
             python manage.py runserver 0.0.0.0:8000"

    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web

    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

    ports:
      - "5432:5432"

    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=ahamadashiq95@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  postgres-pgadmin:

volumes:
  local_pgdata:
  pgadmin-data:
