base:
  project: mlops-insurance
  random_state : 20
  target_col : charges

data_source:
  s3_source: data/raw/insurance_internship.csv

load_data:
  raw_dataset_csv: data/raw/insurance_internship.csv

split_data:
  train_path: data/processed/train_insurance_internship.csv
  test_path : data/processed/test_insurance_internship.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.6
      l1_ration: 0.8

model_dirs: 
  model_dir : models

reports:
  params: reports/params.json
  score: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet_Expenses
  run_name: mlops
  #registered_model_name: ElasticNetMedicalExpenses
  registered_model_name : abc
  #remote_server_uri: https://dagshub.com/ahamadashiq95/regression.mlflow
  remote_server_uri : http://127.0.0.1:5000